origin_host: diameter-local.example
origin_realm: example
listen:
  address: 0.0.0.0:3868
  tls: false
redis:
  addr: redis:6379
postgres:
  dsn: postgres://diam:diam@postgres:5432/diameter?sslmode=disable
peers: []
